apiVersion: v1
kind: Service
metadata:
  name: matilda-server-v1
spec:
  type: LoadBalancer
  ports:
    - name: matilda-server
      port: 80
      targetPort: 5000
  selector:
    app: matilda-server
    version: v1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: matilda-server-v1
spec:
  replicas: 1
  selector:
    app: matilda-server
    version: v1
  template:
    metadata:
      labels:
        app: matilda-server
        version: v1
    spec:
      containers:
        - name: matilda-server
          image: gcr.io/matilda-7/matilda-server:latest
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 5000
